#!/usr/bin/env node

var PORT = 8080;
var HOST = '127.0.0.1';
var APP_FILE = 'index.html';

var MIME_TYPES = {
  png: 'image/png',
  svg: 'image/svg+xml',
  css: 'text/css',
  js: 'application/javascript',
  html: 'text/html'
};

for (var i = 2; i < process.argv.length; i++) {
  var arg = process.argv[i++];
  switch (arg) {
    case '-p': PORT = Number(process.argv[i++]); break;
    default: APP_FILE = arg; break;
  }
}

var http = require('http');
var fs = require('fs');

http.createServer(function(req, res) {

  var st = /^\/static\/.+$/.exec(req.url);
  var file = st ? st[0] : '/' + APP_FILE;

  var mime = MIME_TYPES[file.split('.').pop()] || 'text/plain';

  fs.readFile(__dirname + file, function(err, data) {
    if (err) {
      res.writeHead(404);
      return res.end('Not found.');
    }
    res.writeHead(200, {
      'Content-Length': data.length,
      'Content-Type': mime
    });
    res.end(data);
  });

}).listen(PORT, HOST);
console.log('Server running at http://' + HOST + ':' + PORT + '/');
